<a href="https://colab.research.google.com/github/Serbeld/Tensorflow/blob/master/PlaceHolders.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Clase de Redes**

Redes Neuronales en tensorflow

In [1]:
import tensorflow as tf
print(tf.__version__)

1.15.0


In [0]:
p = tf.placeholder('float',None)

In [0]:
operacion = p + 2

In [4]:
with tf.Session() as sess:
  #sess.run(operacion)
  resultado = sess.run(operacion, feed_dict = {p:[1,2,3]})
  print(resultado)

[3. 4. 5.]


In [0]:
p2 = tf.placeholder('float',[None,6])

In [0]:
operacion2 = p2*5

In [13]:
with tf.Session() as sess:
  datos = [[1,2,3,4,5,6],[7,8,9,10,11,12]]
  resultado2 = sess.run(operacion2, feed_dict = {p2:datos})
  print(resultado2)

[[ 5. 10. 15. 20. 25. 30.]
 [35. 40. 45. 50. 55. 60.]]
